// Clean-room interoperability schema for the mac-phone-link project.
// Independently authored from observed wire behavior; no vendor source text,
// headers, or comments are reproduced. Field numbers and types reflect the
// on-the-wire protobuf layout (interface facts) required for compatibility.
// SPDX-License-Identifier: MIT
syntax = "proto3";
package maclink.files.v1;

import "maclink/files/v1/metadata.proto";
import "maclink/files/v1/sync.proto";

message StorageInfoPayload {
  int64 available_size_bytes = 1;
  int64 total_size_bytes = 2;
}

message FilesThumbnailPrefetchMessage {
  string name = 1;
  string path = 2;
  int32 prefetch_count = 3;
  bool add_to_pictures_library = 4;
}

message FilesConfigurationPayload {
  bool capability = 1;
  bool permission = 2;
  repeated FileType thumbnail_supported_file_types = 3;
  repeated FilesThumbnailPrefetchMessage thumbnail_prefetch_config = 4;
  int64 gigabyte_to_byte = 5;
  string recycle_bin_path = 6;
  bool batch_delete_capability = 7;
  bool is_get_thumbnail_over_nano_mobile_enabled = 8;
  bool is_prefetch_thumbnails_over_nano_mobile_enabled = 9;
  bool is_files_request_over_nano_capable = 10;
  bool is_wifip2p_permission_manager_capable = 11;
  bool is_wifip2p_permissions_granted = 12;
  bool is_image_semantic_search_permission_granted = 13;
}

message FilesSyncUpdateMessage {
  FilesSyncType sync_type = 1;
  int64 seq_num = 2;
}

message FilesResponsePayload {
  oneof payload {
    FilesConfigurationPayload file_configuration = 1;
    FilesSyncUpdateMessage file_sync_update = 2;
    StorageInfoPayload storage_info = 3;
  }
}
