// Clean-room interoperability schema for the mac-phone-link project.
// Independently authored from observed wire behavior; no vendor source text,
// headers, or comments are reproduced. Field numbers and types reflect the
// on-the-wire protobuf layout (interface facts) required for compatibility.
// SPDX-License-Identifier: MIT
syntax = "proto3";
package maclink.files.v1;

enum FilesResponseStatus {
  FILES_RESPONSE_STATUS_UNSPECIFIED = 0;
  FILES_RESPONSE_STATUS_SUCCESS = 1;
  FILES_RESPONSE_STATUS_NO_PERMISSION = 2;
  FILES_RESPONSE_STATUS_NOT_FOUND = 3;
  FILES_RESPONSE_STATUS_CHECKSUM_MISMATCH = 4;
  FILES_RESPONSE_STATUS_IO_ERROR = 5;
  FILES_RESPONSE_STATUS_NOT_SUPPORTED = 6;
  FILES_RESPONSE_STATUS_REQUEST_NOT_SET = 7;
  FILES_RESPONSE_STATUS_FEATURE_DISABLED = 8;
  FILES_RESPONSE_STATUS_PLATFORM_ERROR = 9;
  FILES_RESPONSE_STATUS_CANCELLED = 10;
  FILES_RESPONSE_STATUS_SYNC_FAILED = 11;
  FILES_RESPONSE_STATUS_BATCH_RESTART_REQUIRED = 12;
}
