// Clean-room interoperability schema for the mac-phone-link project.
// Independently authored from observed wire behavior; no vendor source text,
// headers, or comments are reproduced. Field numbers and types reflect the
// on-the-wire protobuf layout (interface facts) required for compatibility.
// SPDX-License-Identifier: MIT
syntax = "proto3";
package maclink.files.v1;
option swift_prefix = "MLFiles";

import "maclink/files/v1/status.proto";

enum FilesSyncType {
  FILES_SYNC_TYPE_UNSPECIFIED = 0;
  FILES_SYNC_TYPE_FULL_SYNC = 1;
  FILES_SYNC_TYPE_INCREMENTAL_SYNC = 2;
}

message FilesConfigurationSyncRequest {}

message FilesSyncRequest {
  oneof request {
    FilesConfigurationSyncRequest config_sync_request = 1;
  }
}

message FilesSyncResponse {
  FilesResponseStatus status = 1;
}
