// Clean-room interoperability schema for the mac-phone-link project.
// Independently authored from observed wire behavior; no vendor source text,
// headers, or comments are reproduced. Field numbers and types reflect the
// on-the-wire protobuf layout (interface facts) required for compatibility.
// SPDX-License-Identifier: MIT
syntax = "proto3";
package maclink.platform.v1;

import "maclink/platform/v1/trace_context.proto";

enum CSInitializeStatus {
  CS_INITIALIZE_STATUS_UNSPECIFIED = 0;
  CS_INITIALIZE_STATUS_SUCCESS = 1;
  CS_INITIALIZE_STATUS_ERROR = 2;
  CS_INITIALIZE_STATUS_ERROR_DEVICE_CONNECTION_FAILURE = 3;
}

message CSIdentityChallenge {
  bytes challenge = 1;
  string requester_dcg_client_id = 2;
  TraceContext trace_context = 3;
}

message CSIdentityResponse {
  bytes challenge = 1;
  string dcg_client_id = 2;
  TraceContext trace_context = 3;
}

message CSInitializeMessage {
  string context_source_id = 2;
  TraceContext trace_context = 4;
  int32 transport_preference = 5;
}

message CSInitializeAckMessage {
  CSInitializeStatus status = 3;
  TraceContext trace_context = 4;
}

message CSOpenDeviceConnectionRequest {
  string scenario_id = 1;
  TraceContext trace_context = 2;
}

message CSConnectionInfo {
  string connection_info = 1;
  TraceContext trace_context = 2;
}

message CSErrorInfo {
  string context_source_error_type = 1;
  TraceContext trace_context = 2;
}

message CSWifiP2pInfo {
  string p2p_info = 1;
  TraceContext trace_context = 2;
}

message ContextSourceMessage {
  oneof type {
    CSInitializeMessage cs_initialize_message = 1;
    CSInitializeAckMessage cs_initialize_ack_message = 2;
    CSOpenDeviceConnectionRequest cs_open_device_connection_request = 3;
    CSConnectionInfo cs_connection_info = 8;
    CSErrorInfo cs_error_info = 9;
    CSWifiP2pInfo cs_wifi_p2p_info = 10;
    CSIdentityChallenge cs_identity_challenge = 11;
    CSIdentityResponse cs_identity_response = 12;
  }
}
