// Clean-room interoperability schema for the mac-phone-link project.
// Independently authored from observed wire behavior; no vendor source text,
// headers, or comments are reproduced. Field numbers and types reflect the
// on-the-wire protobuf layout (interface facts) required for compatibility.
// SPDX-License-Identifier: MIT
syntax = "proto3";
package maclink.platform.v1;

import "maclink/platform/v1/trace_context.proto";

enum ChannelType {
  CHANNEL_TYPE_UNSPECIFIED = 0;
  CHANNEL_TYPE_NAMED_STREAMS = 1;
  CHANNEL_TYPE_VIDEO_STREAMING = 2;
  CHANNEL_TYPE_INTERNAL_MESSAGING = 3;
  CHANNEL_TYPE_MESSAGING = 4;
  CHANNEL_TYPE_VIDEO_TARGET = 5;
  CHANNEL_TYPE_BLOB = 6;
  CHANNEL_TYPE_INPUT_SOURCE = 7;
  CHANNEL_TYPE_AUDIO_TARGET = 8;
  CHANNEL_TYPE_APP_REMOTE = 9;
}

enum CreateChannelStatus {
  CREATE_CHANNEL_STATUS_UNSPECIFIED = 0;
  CREATE_CHANNEL_STATUS_SUCCESS = 1;
  CREATE_CHANNEL_STATUS_FAILURE = 2;
  CREATE_CHANNEL_STATUS_NO_REMOTE_SCENARIO_AVAILABLE = 3;
  CREATE_CHANNEL_STATUS_REMOTE_SCENARIO_REJECTED = 4;
}

enum ChannelAcceptanceStatus {
  CHANNEL_ACCEPTANCE_STATUS_UNSPECIFIED = 0;
  CHANNEL_ACCEPTANCE_STATUS_SUCCESS = 1;
  CHANNEL_ACCEPTANCE_STATUS_PERMISSION_REVOKED = 2;
  CHANNEL_ACCEPTANCE_STATUS_APP_DISABLED = 3;
  CHANNEL_ACCEPTANCE_STATUS_MOBILE_DATA_DISABLED = 4;
  CHANNEL_ACCEPTANCE_STATUS_NOT_SUPPORTED = 5;
  CHANNEL_ACCEPTANCE_STATUS_INVALID_SCENARIO = 6;
  CHANNEL_ACCEPTANCE_STATUS_NO_CALLBACK_PROVIDED = 7;
}

message CreateChannelRequest {
  ChannelType type = 1;
  string scenario_id = 2;
  string channel_id = 3;
  TraceContext trace_context = 4;
  map<string, string> additional_properties = 5;
}

message PeerChannelCreationResult {
  ChannelType type = 1;
  string scenario_id = 2;
  CreateChannelStatus result_code = 3;
  TraceContext trace_context = 4;
  ChannelAcceptanceStatus result_reason = 5;
  string channel_id = 6;
}
