// Clean-room interoperability schema for the mac-phone-link project.
// Independently authored from observed wire behavior; no vendor source text,
// headers, or comments are reproduced. Field numbers and types reflect the
// on-the-wire protobuf layout (interface facts) required for compatibility.
// SPDX-License-Identifier: MIT
syntax = "proto3";
package maclink.platform.v1;

import "maclink/platform/v1/trace_context.proto";

enum PlatformDisconnectRequestReason {
  PLATFORM_DISCONNECT_REQUEST_REASON_UNSPECIFIED = 0;
  PLATFORM_DISCONNECT_REQUEST_REASON_USER_REQUESTED = 1;
  PLATFORM_DISCONNECT_REQUEST_REASON_ALL_SYNC_DISABLED = 2;
  PLATFORM_DISCONNECT_REQUEST_REASON_METERED_SYNC_DISABLED = 3;
  PLATFORM_DISCONNECT_REQUEST_REASON_ACTIVE_SESSION_REPLACED = 4;
  PLATFORM_DISCONNECT_REQUEST_REASON_NON_DEFAULT_USER_OR_PROFILE = 5;
  PLATFORM_DISCONNECT_REQUEST_REASON_TWO_PHONE_MODE_ENABLED = 6;
}

message PlatformDisconnectRequest {
  TraceContext trace_context = 1;
  PlatformDisconnectRequestReason reason = 2;
}
