// Clean-room interoperability schema for the mac-phone-link project.
// Independently authored from observed wire behavior; no vendor source text,
// headers, or comments are reproduced. Field numbers and types reflect the
// on-the-wire protobuf layout (interface facts) required for compatibility.
// SPDX-License-Identifier: MIT
syntax = "proto3";
package maclink.platform.v1;
option swift_prefix = "MLPlatform";

message TraceContext {
  string trace_id = 1;
  string parent_id = 2;
  string correlation_id = 3;
  map<string, string> trace_state = 4;
}
